Repository replit/crosis, pull requests merged in 2020-12, with the labels that each got.

#72 Fix CI
  .eslintrc.js
  .github/workflows/main.yml
  package.json
  src.browser/index.js
  src/EIOCompat.ts
  src/channel.ts
  src/client.ts
  src/utf8_spooky_monkeypatch.ts
Labels: bop

#70 Allow specifying a different URL to connect to in the EIO compat
  src/client.ts
Labels: bop

#73 Allow fetchConnectionMetadata to fail with a recoverable error
  src/__tests__/index.test.ts
  src/client.ts
  src/index.ts
  src/types.ts
Labels: boop

#74 Tweak the fetchConnectionMetadata's result interface a bit
  src/__tests__/index.test.ts
  src/client.ts
  src/index.ts
  src/types.ts
Labels: bop

#75 Fix CI
  .eslintrc.js
  .github/workflows/main.yml
  package.json
  scripts/test.sh
  src/__tests__/index.test.ts
  src/channel.ts
  src/client.ts
  src/types.ts
  src/util/EIOCompat.ts
  src/util/helpers.ts
  src/util/utf8ReadMonkeypatch.ts
  yarn.lock
Labels: hefty

#78 add a debug server
  README.md
  package.json
  src/__tests__/index.test.ts
  src/debug/debug.ts
  src/debug/genConnectionMetadata.d.ts
  src/debug/genConnectionMetadata.js
  src/debug/server.js
  src/debug/webpack.config.js
  yarn.lock
Labels: hefty

#76 Fix a couple of tests (and merge #77)
  .github/workflows/main.yml
  src.browser/index.js
  src/__tests__/index.test.ts
  src/client.ts
Labels: bop

#81 Add some breadcrumbs to figure out chan0CleanupCb error
  src/client.ts
Labels: bop
